name: CI/CD

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  ci:
    name: Test and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run make init to initialize build env
        run: make init

      - name: Build and Test
        run: make test

  deploy:
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Compute APP_TAG
        id: app_tag
        run: echo "tag=$(make app-tag)" >> $GITHUB_OUTPUT

      - name: Inject APP_TAG
        run: sed -i "s/__COMMIT_SHA__/${{ steps.app_tag.outputs.tag }}/g" site/index.html

      - name: Deploy to Cloudflare Pages
        run: npx wrangler pages deploy site --project-name=global-autonomy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
